const types = {
    "SET_INITIAL_PROFILE": "SET_INITIAL_PROFILE",
    "UPDATE_NAME": "UPDATE_NAME",
    "UPDATE_NATION": "UPDATE_NATION",
    "GET_COUNTRIES_LOADING": "GET_COUNTRIES_LOADING",
    "GET_COUNTRIES_SUCCESS": "GET_COUNTRIES_SUCCESS",
    "GET_COUNTRIES_ERROR": "GET_COUNTRIES_ERROR"
};

export default types;
